### ISSUE TITLE
o.from is not a function when attempting `copilot-login`

### ISSUE THREAD

**Issue by jleonard-r7** [zerolfx/copilot.el#67]
```
helm-M-x-execute-command: jsonrpc-error: "request id=57 failed:", (jsonrpc-error-code . -32603), (jsonrpc-error-message . "Request signInInitiate failed with message: o.from is not a function"), (jsonrpc-error-data)
```

**Comment by jleonard-r7** [comment]
Including the output from `copilot-diagnose`:

```
Copilot agent started.
Copilot error: (:code 1000 :message "Not authenticated: NotSignedIn")
helm-M-x-execute-command: jsonrpc-error: "request id=4 failed:", (jsonrpc-error-code . -32603), (jsonrpc-error-message . "Request signInInitiate failed with message: o.from is not a function"), (jsonrpc-error-data)
```

**Comment by jleonard-r7** [comment]
Spacemacs 0.999.0@28.2.

**Comment by zerolfx** [comment]
Please include your NodeJS version.

**Comment by jleonard-r7** [comment]
12.16.3

**Comment by zerolfx** [comment]
Are you using Apple Silicon?
Can you try NodeJS 16.x?

**Comment by jleonard-r7** [comment]
Nope, Intel. 
I just tried with 18.11.0 and am getting the same error.
I had to install `exec-path-from-shell` to get emacs to see my nvm version. But I verified using `shell` (and ielm `(executable-find "node")`) that the `node --version` it sees is the one i listed above.

**Comment by jleonard-r7** [comment]
Ok, it's working with 16.17.1. Looks like older and newer versions do not work (which is non-optimal really). Consider supporting latest versions of node. Thanks!

**Comment by zerolfx** [comment]
This project is based on [copilot.vim](https://github.com/github/copilot.vim), which has restrictions on the version of NodeJS. So I can't do anything about it.

By the way, you can use the variable `copilot-node-executable` to designate the Node executable.

**Comment by jleonard-r7** [comment]
Yea I saw that after the fact but I think the shell path utility I integrated is probably better for my setup long term & for other software so I’ll just leave it that way. PEBKAC bites again, sorry for the churn. 🤣
